#   Sistema
sistema.titulo=ZEggs
sistema.footer=ZEggs - Todos los Derechos Reservados 2022 - Versi\u00f3n 1.0
#   Login
login.titulo=Bienvenido a ZEggs
login.username=Nombre de Usuario
login.password=Contrase\u00f1a
login.recordarme=Recordarme
login.olvidePassword=Olvid\u00e9 la contrase\u00f1a
login.ingresar=Ingresar
#   Principal
principal.titulo=Principal
#   Sidebar
sidebar.salir=Salir
sidebar.principal=Principal
sidebar.consulta=Consultas
sidebar.consulta.cuentaPendiente=Cuenta Pendiente
sidebar.mantenimiento=Mantenimientos
sidebar.mantenimiento.agregarCarton=Agregar Cartones
sidebar.mantenimiento.agregarProducto=Agregar Producto
#   Configuracion
config.barraLateral=Modo Men\u00fa
config.estatico=Est\u00e1tico
config.colorMenu=Color del Men\u00fa
config.claro=Claro
config.oscuro=Oscuro
config.estiloEntrada=Estilo
config.contorno=Contorno
config.lleno=Lleno
config.barraSuperior=Barra Superior
config.tema=Temas
#   Consulta / Cuenta Pendiente
consulta.cuentaPendiente.titulo=Cuenta Pendiente
consulta.cuentaPendiente.tablaVacia=No hay cartones registrados
consulta.cuentaPendiente.tablaTitulo=Lista cartones registrados
consulta.cuentaPendiente.fecha=Fecha
consulta.cuentaPendiente.cantidad=Cantidad
consulta.cuentaPendiente.estado=Estado
consulta.cuentaPendiente.precio=Precio
consulta.cuentaPendiente.total=Total pendiente:
#   Mantenimiento / Agregar Carton
mantenimiento.agregarCarton.titulo=Agregar Cartones
mantenimiento.agregarCarton.usuario=Usuario
mantenimiento.agregarCarton.cantidad=Cantidad
mantenimiento.agregarCarton.precio=Precio
mantenimiento.agregarCarton.estado=Estado
mantenimiento.agregarCarton.guardar=Guardar
mantenimiento.agregarCarton.cancelar=Cancelar
#   EOF
mantenimiento.agregarProducto.titulo=Agregar Producto
mantenimiento.agregarProducto.grupo=Grupo
mantenimiento.agregarProducto.cantidad=Cantidad
mantenimiento.agregarProducto.guardar=Guardar
mantenimiento.agregarProducto.cancelar=Cancelar
