#   Sistema
sistema.titulo=ZEggs
sistema.footer=ZEggs - Todos los Derechos Reservados 2022 - Versi\u00f3n 1.0
#   Login
login.titulo=Bienvenido a ZEggs
login.username=Nombre de Usuario
login.password=Contrase\u00f1a
login.recordarme=Recordarme
login.olvidePassword=Olvid\u00e9 la contrase\u00f1a
login.ingresar=Ingresar
#   Principal
principal.titulo=Principal
#   Sidebar
sidebar.salir=Salir
sidebar.principal=Principal
sidebar.consulta=Consultas
sidebar.consulta.cuentaPendiente=Cuenta Pendiente
sidebar.mantenimiento=Mantenimientos
sidebar.mantenimiento.agregarCarton=Agregar Cartones
#   Consulta / Cuenta Pendiente
consulta.cuentaPendiente.titulo=Cuenta Pendiente
consulta.cuentaPendiente.tablaVacia=No hay cartones registrados
consulta.cuentaPendiente.tablaTitulo=Lista cartones registrados
consulta.cuentaPendiente.fecha=Fecha
consulta.cuentaPendiente.cantidad=Cantidad
consulta.cuentaPendiente.estado=Estado
consulta.cuentaPendiente.precio=Precio
consulta.cuentaPendiente.total=Total pendiente:
#   Mantenimiento / Agregar Carton

mantenimiento.agregarCarton.titulo=Agregar Cartones
